#!/usr/bin/env python3
"""
Generate compressed MNIST data for the PCA demo.

Downloads full MNIST (28x28) via fetch_openml, subsamples 400 images per digit
(4000 total), compresses with zlib + base64, and writes to apps/_mnist_data.py.

Usage:
    python scripts/generate_mnist_data.py

Requirements:
    pip install scikit-learn numpy
"""

import base64
import io
import zlib

import numpy as np
from sklearn.datasets import fetch_openml


def main():
    print("Downloading MNIST from OpenML...")
    mnist = fetch_openml("mnist_784", version=1, as_frame=False, parser="auto")
    X_full = mnist.data.astype(np.uint8)  # (70000, 784), uint8
    y_full = mnist.target.astype(np.int8)  # (70000,)

    print(f"Full dataset: {X_full.shape[0]} samples, {X_full.shape[1]} features")

    # Subsample 400 per digit for balanced classes (4000 total)
    samples_per_digit = 400
    rng = np.random.default_rng(42)

    indices = []
    for digit in range(10):
        digit_indices = np.where(y_full == digit)[0]
        chosen = rng.choice(digit_indices, size=samples_per_digit, replace=False)
        indices.append(chosen)

    indices = np.concatenate(indices)
    rng.shuffle(indices)

    X = X_full[indices]
    y = y_full[indices]

    print(f"Subsampled: {X.shape[0]} samples ({samples_per_digit} per digit)")

    # Compress: save as uncompressed npz, then zlib + base64
    # (npz_compressed uses zip internally, so outer zlib adds nothing;
    #  using uncompressed npz + zlib gives better overall compression)
    buf = io.BytesIO()
    np.savez(buf, X=X, y=y)
    raw = buf.getvalue()
    compressed = zlib.compress(raw, level=9)
    encoded = base64.b64encode(compressed).decode("ascii")

    print(f"Raw npz: {len(raw):,} bytes")
    print(f"zlib compressed: {len(compressed):,} bytes")
    print(f"base64 encoded: {len(encoded):,} chars")

    # Write to apps/_mnist_data.py
    output_path = "apps/_mnist_data.py"
    with open(output_path, "w") as f:
        f.write('"""Auto-generated MNIST data for PCA demo.\n')
        f.write("\n")
        f.write("Contains 4000 samples (400 per digit) of 28x28 handwritten digits.\n")
        f.write("Generated by: python scripts/generate_mnist_data.py\n")
        f.write('"""\n\n')
        f.write("# base64(zlib(npz)) — decode with:\n")
        f.write("#   buf = io.BytesIO(zlib.decompress(base64.b64decode(MNIST_DATA_B64)))\n")
        f.write("#   npz = np.load(buf); X = npz['X']; y = npz['y']\n")
        f.write(f'MNIST_DATA_B64 = "{encoded}"\n')

    import os

    file_size = os.path.getsize(output_path)
    print(f"\nWrote {output_path} ({file_size:,} bytes)")


if __name__ == "__main__":
    main()
